nums: 1
g: 9.81
quadrotor: "xi35.yaml"
dt: 0.01
control_mode: "SRT" # "CTBR" or "CTBM" or "SRT" 
noise_std:  [0.01,0.01,0.01, #pos
              0.01,0.01,0.01, #vel
              0.001,0.001,0.001,0.001, #quaternion
              0.001,0.001,0.001, #ang_vel
              0.01,0.01,0.01,0.01, #m1 m2 m3 m4
            ]